spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.17.100.13:3306/z_user?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
        username: root
        password: root
    session:
        store-type: REDIS
    redis:
        host: 127.0.0.1
        port: 6379




#security:
#    basic:
#        enabled: false

#security.user.name: lisi
#security.user.password: 123456
#wang.security.browser.loginPage: /demo-signin.html
#wang.security.browser.type: JSON
wang.security.browser.type: REDIRECT
#wang.security.browser.signOutUrl: /demo-signout.html
#wang.security.browser.signInUrl: /index.html
#wang.security.browser.signUpUrl: /wang-regist.html
#wang.security.browser.signUpUrl: /wangSignUp
#wang.security.code.image.length: 6
#wang.security.code.image.width: 1000
#wang.security.code.image.url: /user,/user/*


#wang.security.social.weixin.appId: wx32e49510d80d1034
#wang.security.social.weixin.appSecret: 2a33cd6b66c28a8e1e2d1894b042a1ca
#wang.security.social.filterProcessesUrl: /check

wang.security.oauth2.clients[0].clientId: wang
wang.security.oauth2.clients[0].clientSecret: wang123456
wang.security.oauth2.clients[0].accesstokenInvalidSeconds: 7200
wang.security.oauth2.clients[0].scopes: all,read,write
wang.security.oauth2.clients[0].grandType: authorization_code,password,implicit,client_credentials,refresh_token

wang.security.oauth2.clients[1].clientId: xia
wang.security.oauth2.clients[1].clientSecret: xia123456
wang.security.oauth2.clients[1].accesstokenInvalidSeconds: 1800
wang.security.oauth2.clients[1].scopes: all
wang.security.oauth2.clients[1].grandType: password
# wang.security.oauth2.jwtSignKey: wang...
#wang.security.oauth2.tokenStore: redis

server:
    port: 80
#    session:
#        timeout: 10






